version: '3.3'
services:
  form_storybook:
    image: uicore-storybook:latest
    ports:
      - '3000:3000'
    expose:
      - '3000'
    build:
      context: .
      dockerfile: Dockerfile.storybook